apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: fmtf0jc4g-java-quarkus-gitops-repository
spec:
  url: https://github.com/rhtap-rhdh-qe/fmtf0jc4g-java-quarkus-gitops